using System.Collections;
using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

namespace BugFarmer.UI
{
    /// <summary>
    /// The game's OPENING: a short text intro ("It is 2136…") that reveals one line at a time, then
    /// crossfades to the BugFarmer TITLE screen (a composed farm scene + the logo + a Start button).
    /// Pressing Start hides this overlay to reveal the CharacterSelectPanel beneath — which has been
    /// authenticating + loading the roster the whole time (so the intro doubles as the loading cover).
    ///
    /// Self-bootstrapping like CharacterSelectPanel/UIBootstrap (zero scene wiring): its own top canvas
    /// at sortingOrder 30 (above char-select's 20), opaque, so it owns the whole screen until dismissed.
    /// Plays ONCE per app launch. Skippable — click / Space / Esc fast-forwards to the title.
    ///
    /// Art: Resources/UI/title_bg (1280x720 scene) + Resources/UI/title_logo (the wordmark), generated by
    /// tools/sprites/title_art.py. Missing art degrades to a solid bg + a TMP "BugFarmer" wordmark.
    /// </summary>
    public class OpeningSequence : MonoBehaviour
    {
        // ----------------------------------------------------------------- the script (EDIT HERE)
        // PLACEHOLDER intro — replace with Andrew's pasted script. Line 1 is his ("It is 2136."); the
        // rest is my stand-in. Blank "" entries are deliberate beats/spacers. One line == one reveal.
        private static readonly string[] IntroLines =
        {
            "It is 2136.",
            "",
            "The old world's harvests failed, one by one —",
            "the fields went quiet, the great herds gone.",
            "",
            "But where everything else faltered,",
            "the smallest creatures thrived.",
            "",
            "Now the swarms are our livestock, our trade, our hope.",
            "On the frontier, a few hardy souls tend them,",
            "and coax the tired soil back to life.",
            "",
            "You are one of them.",
        };

        private const float LineFadeIn = 0.7f;   // seconds for a line to fade in
        private const float LineGap = 0.55f;      // pause after a line before the next
        private const float HoldAfter = 1.6f;     // hold on the full text before the title
        private const float CrossFade = 1.0f;     // intro->title crossfade
        private const int IntroFontSize = 22;

        private static bool _played;

        private CanvasGroup _root;     // whole overlay (final fade-out)
        private CanvasGroup _intro;    // the text phase
        private CanvasGroup _title;    // the title phase
        private TMP_Text[] _lines;
        private TMP_Text _skipHint;
        private bool _skip;            // fast-forward the intro
        private bool _start;           // Start pressed
        private bool _inIntro = true;

        // ----------------------------------------------------------------- bootstrap
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
        private static void Bootstrap()
        {
            if (_played) return;
            _played = true;

            if (Object.FindObjectOfType<EventSystem>() == null)
            {
                var es = new GameObject("EventSystem(Code)", typeof(EventSystem), typeof(StandaloneInputModule));
                Object.DontDestroyOnLoad(es);
            }

            var go = new GameObject("OpeningCanvas(Code)", typeof(Canvas), typeof(CanvasScaler),
                                    typeof(GraphicRaycaster));
            var canvas = go.GetComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;
            canvas.sortingOrder = 30; // above char-select (20), inventory (10), scene menu (0)
            var scaler = go.GetComponent<CanvasScaler>();
            scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            scaler.referenceResolution = new Vector2(800, 600);
            scaler.matchWidthOrHeight = 0.5f;
            go.AddComponent<OpeningSequence>();
        }

        private bool _failed;

        private void Awake()
        {
            // Build in Awake (runs synchronously when Bootstrap AddComponents this) so the opaque
            // overlay covers the char-select canvas from the first frame — no 1-frame flash.
            // FAIL-SAFE: if anything here throws, tear the overlay down so the launch is never blocked —
            // the CharacterSelectPanel beneath is then reachable as if the opening didn't exist.
            try
            {
                UIFactory.Stretch((RectTransform)transform, 0);
                _root = gameObject.AddComponent<CanvasGroup>();
                BuildIntro();
                BuildTitle();
            }
            catch (System.Exception e)
            {
                Debug.LogError($"[OpeningSequence] build failed, skipping opening: {e}");
                _failed = true;
                Destroy(gameObject);
            }
        }

        private void Start()
        {
            if (!_failed) StartCoroutine(Run());
        }

        private void Update()
        {
            if (_inIntro && (Input.GetMouseButtonDown(0) || Input.GetKeyDown(KeyCode.Space) ||
                             Input.GetKeyDown(KeyCode.Escape) || Input.GetKeyDown(KeyCode.Return)))
                _skip = true;
        }

        // ----------------------------------------------------------------- build: intro
        private void BuildIntro()
        {
            var panel = UIFactory.MakeRect(transform, "Intro");
            UIFactory.Stretch(panel, 0);
            _intro = panel.gameObject.AddComponent<CanvasGroup>();

            var bg = panel.gameObject.AddComponent<Image>();
            bg.color = new Color(0.05f, 0.06f, 0.09f, 1f); // deep near-black night
            bg.raycastTarget = true;

            // Centered block of lines. Pre-placed (alpha 0), faded in one at a time.
            const float lineH = 30f;
            float total = IntroLines.Length * lineH;
            _lines = new TMP_Text[IntroLines.Length];
            for (int i = 0; i < IntroLines.Length; i++)
            {
                var t = UIFactory.MakeText(panel, $"Line{i}", IntroFontSize,
                                           new Color(0.92f, 0.90f, 0.82f, 1f), TextAlignmentOptions.Center);
                t.enableWordWrapping = true;
                var rt = t.rectTransform;
                rt.anchorMin = rt.anchorMax = new Vector2(0.5f, 0.5f);
                rt.pivot = new Vector2(0.5f, 0.5f);
                rt.sizeDelta = new Vector2(720, lineH);
                rt.anchoredPosition = new Vector2(0, total / 2f - lineH / 2f - i * lineH);
                t.text = IntroLines[i];
                t.alpha = 0f;
                _lines[i] = t;
            }

            _skipHint = UIFactory.MakeText(panel, "SkipHint", 12,
                                           new Color(0.7f, 0.68f, 0.6f, 0.6f), TextAlignmentOptions.Center);
            var hrt = _skipHint.rectTransform;
            hrt.anchorMin = hrt.anchorMax = new Vector2(0.5f, 0f);
            hrt.pivot = new Vector2(0.5f, 0f);
            hrt.sizeDelta = new Vector2(400, 18);
            hrt.anchoredPosition = new Vector2(0, 24);
            _skipHint.text = "click to skip";
        }

        // ----------------------------------------------------------------- build: title
        private void BuildTitle()
        {
            var panel = UIFactory.MakeRect(transform, "Title");
            UIFactory.Stretch(panel, 0);
            _title = panel.gameObject.AddComponent<CanvasGroup>();
            _title.alpha = 0f;
            panel.gameObject.SetActive(false);

            // Background scene (stretch-fill). Fallback solid sky if art missing.
            var bg = panel.gameObject.AddComponent<Image>();
            var bgTex = Resources.Load<Texture2D>("UI/title_bg");
            if (bgTex != null)
                bg.sprite = Sprite.Create(bgTex, new Rect(0, 0, bgTex.width, bgTex.height), new Vector2(0.5f, 0.5f), 100f);
            else
                bg.color = new Color(0.59f, 0.77f, 0.88f, 1f);
            bg.raycastTarget = true;

            // Logo (upper third), preserve aspect. Fallback to a styled TMP wordmark.
            var logoTex = Resources.Load<Texture2D>("UI/title_logo");
            if (logoTex != null)
            {
                var logo = UIFactory.MakeImage(panel, "Logo", null);
                logo.sprite = Sprite.Create(logoTex, new Rect(0, 0, logoTex.width, logoTex.height), new Vector2(0.5f, 0.5f), 100f);
                logo.preserveAspect = true;
                var lr = logo.rectTransform;
                lr.anchorMin = lr.anchorMax = new Vector2(0.5f, 1f);
                lr.pivot = new Vector2(0.5f, 1f);
                lr.sizeDelta = new Vector2(560, 163); // ~1100x320 aspect, scaled into the 800x600 ref
                lr.anchoredPosition = new Vector2(0, -70);
            }
            else
            {
                var word = UIFactory.MakeText(panel, "Wordmark", 64, UIFactory.HeaderColor, TextAlignmentOptions.Center);
                word.fontStyle = FontStyles.Bold;
                var wr = word.rectTransform;
                wr.anchorMin = wr.anchorMax = new Vector2(0.5f, 1f); wr.pivot = new Vector2(0.5f, 1f);
                wr.sizeDelta = new Vector2(700, 90); wr.anchoredPosition = new Vector2(0, -90);
                word.text = "BugFarmer";
            }

            // Start button (lower-center), styled like the other code-built buttons.
            var btnRt = UIFactory.MakeRect(panel, "StartBtn");
            btnRt.anchorMin = btnRt.anchorMax = new Vector2(0.5f, 0f);
            btnRt.pivot = new Vector2(0.5f, 0f);
            btnRt.sizeDelta = new Vector2(220, 56);
            btnRt.anchoredPosition = new Vector2(0, 70);
            var btnImg = btnRt.gameObject.AddComponent<Image>();
            btnImg.sprite = UIFactory.UISprite("panel_wood");
            btnImg.type = Image.Type.Sliced;
            btnImg.color = new Color32(96, 150, 96, 255);
            var btn = btnRt.gameObject.AddComponent<Button>();
            btn.onClick.AddListener(() => _start = true);
            var btnTxt = UIFactory.MakeText(btnRt, "Label", 22, new Color(0.98f, 0.96f, 0.86f, 1f),
                                            TextAlignmentOptions.Center);
            btnTxt.fontStyle = FontStyles.Bold;
            UIFactory.Stretch(btnTxt.rectTransform, 4);
            btnTxt.text = "Start";
        }

        // ----------------------------------------------------------------- sequence
        private IEnumerator Run()
        {
            // 1) reveal the intro lines one at a time (skippable).
            for (int i = 0; i < _lines.Length; i++)
            {
                if (_skip) break;
                if (string.IsNullOrEmpty(IntroLines[i])) { _lines[i].alpha = 1f; continue; }
                yield return Fade(a => _lines[i].alpha = a, 0f, 1f, LineFadeIn);
                yield return WaitOrSkip(LineGap);
            }
            // ensure all visible (covers the skip path)
            for (int i = 0; i < _lines.Length; i++) _lines[i].alpha = 1f;
            yield return WaitOrSkip(HoldAfter);

            // 2) crossfade intro -> title.
            _inIntro = false;
            if (_skipHint != null) _skipHint.gameObject.SetActive(false);
            _title.gameObject.SetActive(true);
            float t = 0f;
            while (t < CrossFade)
            {
                t += Time.unscaledDeltaTime;
                float k = Mathf.Clamp01(t / CrossFade);
                _intro.alpha = 1f - k;
                _title.alpha = k;
                yield return null;
            }
            _intro.alpha = 0f; _title.alpha = 1f;
            _intro.gameObject.SetActive(false);

            // 3) wait for Start, then fade the whole overlay out and reveal char-select.
            while (!_start) yield return null;
            yield return Fade(a => _root.alpha = a, 1f, 0f, 0.5f);
            Destroy(gameObject); // free the overlay; CharacterSelectPanel (order 20) is now in front
        }

        private IEnumerator Fade(System.Action<float> set, float from, float to, float dur)
        {
            float t = 0f;
            while (t < dur)
            {
                t += Time.unscaledDeltaTime;
                set(Mathf.Lerp(from, to, Mathf.Clamp01(t / dur)));
                yield return null;
            }
            set(to);
        }

        private IEnumerator WaitOrSkip(float seconds)
        {
            float t = 0f;
            while (t < seconds && !_skip) { t += Time.unscaledDeltaTime; yield return null; }
        }
    }
}
