"""body_frames — the master body template grids (16x32, legend in pixkit).

ONE hand-authored IDLE grid per direction; the walk cycle derives from it:
  contact-L : right leg + left arm shifted 1px up (half-row offset, outline
              rides along), head/torso bobbed 1px down
  passing   : the idle grid itself
  contact-R : mirror of contact-L's shifts
Frame order at runtime: [contact-L, idle, contact-R, idle].

Anatomy rows (16x32, down): hair 1-5 | face 6-12 | neck 13 | shoulders 14 |
torso+arms 15-22 | waistband 23 | legs 24-28 | boots 29-30 | feet line 31.
"""
from . import pixkit


# ---- DOWN (the hero shot) ----------------------------------------------------
DOWN_IDLE = """
................
.....oooooo.....
....oHHHHhho....
...oHHhhhhhho...
...oHhhhhhhgo...
...ohhhhhhhgo...
...ogzSSSSzgo...
...ogSSSSSSgo...
...ogSeSSeSgo...
...ogsessesgo...
...ozsssssszo...
....ossmmsso....
.....ozsszo.....
......osso......
..oTTTTTTTTTTo..
.otttttttttttto.
.otttttttttttuo.
.ostttttttttuso.
..otttttttttuo..
...otttttttuo...
...ottuttttuo...
...ottttuuuuo...
...ouuuuuuuuo...
...ovvvvvvvvo...
...oLllllllvo...
...oLlloollvo...
...ollloolllo...
...ovlloollvo...
...ovvloolvvo...
...oBbboobbBo...
...obbboobbbo...
...oooo..oooo...
"""

# ---- UP (back of head, no face) ----------------------------------------------
UP_IDLE = """
................
.....oooooo.....
....oHHHHhho....
...oHHhhhhhho...
...oHhhhhhhgo...
...ohhhhhhhgo...
...ohhhhhhhgo...
...ohhhhhhggo...
...oghhhhhggo...
...oghhhhgggo...
...ozghhggzzo...
....ozggggzo....
.....ozzzzo.....
......osso......
..oTTTTTTTTTTo..
.otttttttttttto.
.otttttttttttuo.
.ostttttttttuso.
..otttttttttuo..
...otttttttuo...
...otttttttuo...
...ottttttuuo...
...ouuuuuuuuo...
...ovvvvvvvvo...
...oLllllllvo...
...oLlloollvo...
...ollloolllo...
...ovlloollvo...
...ovvloolvvo...
...obbboobbbo...
...obbboobbbo...
...oooo..oooo...
"""

# ---- LEFT (true side view: slim torso, front arm, solid leg block; right = mirror)
LEFT_IDLE = """
................
.....oooooo.....
....oHHHHhho....
...oHHhhhhhho...
...oHhhhhhhho...
...oSShhhhhho...
...oSSShhhhho...
...oSSSghhhho...
...oSeSghhhho...
...osesghhhho...
...osssghhhho...
....omszghho....
.....ozszgo.....
......osso......
...oTTTTTTTTo...
..otttttttttto..
..oTttttttttto..
..oSttttttttto..
...osttttttuo...
...oTtttttuuo...
...oTttttuuuo...
...ottttuuuuo...
...ouuuuuuuuo...
...ovvvvvvvvo...
...oLllllvvvo...
...oLllvllvvo...
...oLllvllvvo...
...olllvllvvo...
...ovllvllvvo...
..oBbbbbbbbo....
..obbbbbbbbo....
..oooooooooo....
"""


def _rows(grid):
    return pixkit.parse(grid)


def _shift_half_up(rows, half, row_lo, row_hi):
    """Within rows[row_lo..row_hi], shift the left or right half UP 1px
    (each half-row takes the half-row below it). Bottom half-row empties."""
    lo, hi = row_lo, row_hi
    out = [list(r) for r in rows]
    w = len(rows[0])
    x0, x1 = (0, w // 2) if half == "left" else (w // 2, w)
    for y in range(lo, hi):
        for x in range(x0, x1):
            out[y][x] = rows[y + 1][x]
    for x in range(x0, x1):
        out[hi][x] = "."
    return ["".join(r) for r in out]


def _bob_down(rows, row_hi):
    """Shift rows[0..row_hi] down 1px (head bob on contact frames)."""
    out = [list(r) for r in rows]
    for y in range(row_hi, 0, -1):
        for x in range(len(rows[0])):
            out[y][x] = rows[y - 1][x]
    for x in range(len(rows[0])):
        out[0][x] = "."
    return ["".join(r) for r in out]


# rows that hold legs/feet per template (same for all directions); arms do
# NOT swing (2026-06 feedback: the shifted-sleeve notch read as an artifact)
LEG_LO, LEG_HI = 25, 31
HEAD_HI = 13


def walk_frames(idle_rows):
    """[contact-L, idle, contact-R, idle] derived from the idle master."""
    a = _shift_half_up(idle_rows, "right", LEG_LO, LEG_HI)   # right leg back/up
    a = _bob_down(a, HEAD_HI)
    b = _shift_half_up(idle_rows, "left", LEG_LO, LEG_HI)
    b = _bob_down(b, HEAD_HI)
    return [a, list(idle_rows), b, list(idle_rows)]


def direction_frames():
    """{dir: [4 frame row-lists]} for all four directions."""
    down = _rows(DOWN_IDLE)
    up = _rows(UP_IDLE)
    left = _rows(LEFT_IDLE)
    right = pixkit.mirror(left)
    return {d: walk_frames(r) for d, r in
            (("down", down), ("up", up), ("left", left), ("right", right))}
