"""player_designs — THREE from-scratch player characters (the redesign gate).

Andrew's brief: chunky, Zelda (LTTP) + Terraria inspired, SAME PERSPECTIVE as
the world art — the 45-degree top-down of PERSPECTIVE_GUIDE.md: hair crown
visible from above, faces below it, and side views are 3/4 TURNS (one eye at
the leading edge, body foreshortened), never a pure profile.

  D1 "SQUIRT"  18x24  LTTP squat chibi — head ~46% of height, big eyes,
               stub limbs, huge readable silhouette at farm zoom.
  D2 "STOUT"   18x28  Terraria chunky — blocky head onto broad neckless
               shoulders, thick limbs, adult-but-thick proportions.
  D3 "BEAN"    16x26  round farmhand — dome head, oval body, OVERALLS with
               a bib (the farm-game identity), soft shapes.

All grids keep the region legend (pixkit: skin/hair/shirt/pants/boots), so
the paper-doll layers/armor keep deriving — wearable grids re-anchor to the
WINNER's template during propagation (one-time cost, flagged).

Run: python3 tools/player_sprites/player_designs.py
-> previews/player/designs/{card.png, D?_left.gif, D?_down.gif}
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
from player_sprites import pixkit  # noqa: E402
from player_sprites.palettes import CLASSES, SKIN_TONES  # noqa: E402

OUT = os.path.normpath(os.path.join(HERE, "..", "_generated", "previews",
                                    "player", "designs"))

# =============================== D1 SQUIRT (18x24) ===========================
# LTTP-squat: hair crown dome (top-down), face fills the lower head, big 2x2
# eyes, tiny body, stub legs. Head rows 0-10, body 11-18, legs 19-23.
D1_DOWN = """
.....oooooooo.....
...ooHHHHHHhhoo...
..oHHHHHHHhhhho...
..oHHhhhhhhhhho...
..ohhhhhhhhhhho...
..ohhSSSSSSSSho...
..ohSSeSSSSeSho...
..ohsSeSSSSeSho...
...ozsSSmmSSzo....
....ozsssssszo....
.....oossoo.......
...oTTTTTTTTTo....
..oTtttttttttto...
..oStttttttttSo...
..ostttttttttso...
...ottttttttto....
...ouutttttuuo....
....ovvvvvvvo.....
....oLLloovvvo....
....oLlloovvvo....
....oLlloovvvo....
...oBblloovvbo....
...obbbooobbbo....
....ooo....ooo....
"""

D1_LEFT = """
.....oooooooo.....
...ooHHHHHHhhoo...
..oHHHHHHHhhhho...
..oHHhhhhhhhhho...
..ohhhhhhhhhhho...
..oSShhhhhhhhho...
..oSeSShhhhhhho...
..oseSShhhhhhho...
...ozsSShhhggo....
....ozssshhgo.....
.....oossoo.......
...oTTTTTTTTTo....
..oTttttttttto....
..oSttttttttto....
..osttttttttto....
...ottttttttuo....
...ouutttttuuo....
....ovvvvvvvo.....
....oLLllvvvvo....
....oLlllvvvvo....
....ollllvvvvo....
...oBbblllvvvo....
...obbbbbbbbo.....
...ooooooooo......
"""

D1_UP = """
.....oooooooo.....
...ooHHHHHHhhoo...
..oHHHHHHHhhhho...
..oHHhhhhhhhhho...
..ohhhhhhhhhhho...
..ohhhhhhhhhhho...
..ohhhhhhhhhhgo...
..ohhhhhhhhgggo...
...oghhhhhgggo....
....ogghggggo.....
.....oossoo.......
...oTTTTTTTTTo....
..oTtttttttttto...
..oStttttttttSo...
..ostttttttttso...
...ottttttttto....
...ouutttttuuo....
....ovvvvvvvo.....
....oLLloovvvo....
....oLlloovvvo....
....oLlloovvvo....
...oBblloovvbo....
...obbbooobbbo....
....ooo....ooo....
"""

# =============================== D2 STOUT (18x28) ============================
# Terraria-chunky: blocky head, NO neck — head sits onto broad shoulders,
# thick 3px arms, tapered torso, thick legs. Head 0-9, torso 10-19, legs 20-27.
D2_DOWN = """
....oooooooooo....
...oHHHHHHHHhho...
..oHHHhhhhhhhho...
..oHHhhhhhhhhho...
..ohhSSSSSSSSho...
..ohSSeSSSSeSho...
..ohsSeSSSSeSho...
..ozssSSSSSSzgo...
...ozsSSmmSSzo....
....ossssssso.....
..oTTTTTTTTTTTTo..
.oTTttttttttttTo..
.oTtttttttttttuo..
.oStttttttttttSo..
.ostttttttttttso..
..ottttttttttto...
..ottttttttttuo...
..ouuttttttuuuo...
...ouuuuuuuuuo....
...ovvvvvvvvvo....
...oLLlloolvvvo...
...oLllloolvvvo...
...oLllloolvvvo...
...olllloollvvo...
...ovllloolvvvo...
..oBbblloolbbvo...
..obbbbooobbbbo...
...oooo....oooo...
"""

D2_LEFT = """
....oooooooooo....
...oHHHHHHHHhho...
..oHHHhhhhhhhho...
..oHHhhhhhhhhho...
..oSShhhhhhhhho...
..oSeSShhhhhhho...
..oseSShhhhhhho...
..ozsSShhhhhggo...
...ozsShhhhggo....
....osshhhggo.....
..oTTTTTTTTTTTo...
.oTTtttttttttto...
.oTttttttttttuo...
.oSttttttttttuo...
.osttttttttttuo...
..otttttttttuo....
..otttttttttuo....
..ouuttttttuuo....
...ouuuuuuuuo.....
...ovvvvvvvvo.....
...oLLlllvvvvo....
...oLllllvvvvo....
...oLllllvvvvo....
...ollllvvvvvo....
...ovlllvvvvvo....
..oBbblllvvvvo....
..obbbbbbbbbo.....
...ooooooooo......
"""

D2_UP = """
....oooooooooo....
...oHHHHHHHHhho...
..oHHHhhhhhhhho...
..oHHhhhhhhhhho...
..ohhhhhhhhhhho...
..ohhhhhhhhhhho...
..ohhhhhhhhhggo...
..oghhhhhhggggo...
...oghhhgggggo....
....ogggggggo.....
..oTTTTTTTTTTTTo..
.oTTttttttttttTo..
.oTtttttttttttuo..
.oStttttttttttSo..
.ostttttttttttso..
..ottttttttttto...
..ottttttttttuo...
..ouuttttttuuuo...
...ouuuuuuuuuo....
...ovvvvvvvvvo....
...oLLlloolvvvo...
...oLllloolvvvo...
...oLllloolvvvo...
...olllloollvvo...
...ovllloolvvvo...
..oBbblloolbbvo...
..obbbbooobbbbo...
...oooo....oooo...
"""

# =============================== D3 BEAN (16x26) =============================
# Round farmhand: dome head, oval body, OVERALLS — the pants region rises as
# a bib + straps over the shirt. Head 0-9, body 10-18, legs 19-25.
D3_DOWN = """
.....oooooo.....
...ooHHHHhhoo...
..oHHHHHHhhhho..
..oHHhhhhhhhho..
..ohhSSSSSShho..
..ohSeSSSSeSho..
..ohseSSSSesho..
...ozSSmmSSzo...
....osssssso....
.....oosso......
...oTTvvvvTTo...
..oTtvLLLLvtTo..
..oStvLllLvtSo..
..ostvLllLvtso..
...otvLlllLvto..
...ouvLlllLvuo..
....ovvvvvvo....
....oLllovvvo...
....oLllovvvo...
....olllovvvo...
...oBbloovvbo...
...obboo.obbo...
....ooo...ooo...
................
................
................
"""

D3_LEFT = """
.....oooooo.....
...ooHHHHhhoo...
..oHHHHHHhhhho..
..oHHhhhhhhhho..
..oSShhhhhhhho..
..oSeSShhhhhho..
..oseSShhhhhho..
...ozsShhhggo...
....osshhggo....
.....oosso......
...oTTvvvvTTo...
..oTtvLLLLvtto..
..oStvLllLvtto..
..ostvLllLvtto..
...otvLlllLvto..
...ouvLlllLvuo..
....ovvvvvvo....
....oLlllvvvo...
....oLlllvvvo...
....ollllvvvo...
...oBbblllvvo...
...obbbbbbbo....
....ooooooo.....
................
................
................
"""

D3_UP = """
.....oooooo.....
...ooHHHHhhoo...
..oHHHHHHhhhho..
..oHHhhhhhhhho..
..ohhhhhhhhhho..
..ohhhhhhhhhho..
..ohhhhhhhhggo..
...oghhhhgggo...
....oggggggo....
.....oosso......
...oTTvvvvTTo...
..oTtvLLLLvtTo..
..oStvLllLvtSo..
..ostvLllLvtso..
...otvLlllLvto..
...ouvLlllLvuo..
....ovvvvvvo....
....oLllovvvo...
....oLllovvvo...
....olllovvvo...
...oBbloovvbo...
...obboo.obbo...
....ooo...ooo...
................
................
................
"""

DESIGNS = {
    "D1_squirt": {"down": D1_DOWN, "left": D1_LEFT, "up": D1_UP, "legs_row": 18},
    "D2_stout": {"down": D2_DOWN, "left": D2_LEFT, "up": D2_UP, "legs_row": 20},
    "D3_bean": {"down": D3_DOWN, "left": D3_LEFT, "up": D3_UP, "legs_row": 17},
}


def _walkframes(rows, legs_row):
    """Gate-preview walk: the picked A-stride idea, generalized — side frames
    shift front/back leg columns apart (short stride per Andrew's note);
    plus the boot-lift alternation. Final cycles are hand-tuned on the winner."""
    w = len(rows[0])
    split = w // 2

    def shift(front_dx, back_dx):
        out = [list("." * w) for _ in rows]
        for y in range(len(rows)):
            if y < legs_row:
                out[y] = list(rows[y])
                continue
            for x, c in enumerate(rows[y]):
                if c == ".":
                    continue
                dx = front_dx if x < split else back_dx
                nx = max(0, min(w - 1, x + dx))
                out[y][nx] = c
        return ["".join(r) for r in out]

    table = str.maketrans({"L": "v", "l": "v", "v": "l"})
    f0 = shift(-1, +1)
    f2 = ["".join(r).translate(table) if y >= legs_row else r
          for y, r in enumerate(shift(0, -1))]
    return [f0, list(rows), f2, list(rows)]


def main():
    hair, shirt, pants = CLASSES["farmer"][1], CLASSES["farmer"][2], CLASSES["farmer"][3]
    pal = pixkit.make_palette(skin=SKIN_TONES["default"], hair=hair,
                              shirt=shirt, pants=pants)
    from PIL import Image
    card = []
    maxw, maxh = 18, 28
    for name, d in DESIGNS.items():
        cells = []
        for dirn in ("down", "left", "up"):
            rows = pixkit.parse(d[dirn])
            bad = sorted({c for r in rows for c in r if c != "." and c not in pal})
            assert not bad, (name, dirn, bad)
            cells.append(pixkit.render(rows, pal, mode="baked"))
        # walk gifs (left + down)
        for dirn in ("left", "down"):
            frames = _walkframes(pixkit.parse(d[dirn]), d["legs_row"])
            imgs = [pixkit.render(f, pal, mode="baked") for f in frames]
            pixkit.walk_gif(imgs, os.path.join(OUT, f"{name}_{dirn}.gif"), scale=8)
            cells.append(imgs[0])   # the contact pose on the card
        # pad cells onto a uniform canvas for the sheet
        for im in cells:
            c = Image.new("RGBA", (maxw, maxh), (0, 0, 0, 0))
            c.paste(im, ((maxw - im.width) // 2, maxh - im.height), im)
            card.append(c)
    pixkit.save(pixkit.contact_sheet(card, cols=5, scale=8),
                os.path.join(OUT, "card.png"))
    print(f"designs -> {OUT} (rows: D1 squirt, D2 stout, D3 bean; "
          f"cols: down, left, up, left-contact, down-step)")


if __name__ == "__main__":
    main()
