"""player_designs2 — NEW characters built to the SNES-Zelda reference (zelda.png).

What the reference establishes (measured): head ~60%% of sprite height with the
hair/hat CROWN seen from above; hair tufts wider than the body; eyes small and
LOW on the face; tunic ~6 rows; feet = nubs directly under the body; 2-frame
forward walk that is (nearly) a horizontal mirror. Strong outline, saturated
2-3 step ramps.

Three NEW identities (no teal farmer):
  C1 "SCOUT"    straw hat + ginger tufts, olive tunic, satchel strap — the
                farm adventurer.
  C2 "JUNIPER"  dark bob + sky-blue overall dress over cream shirt — the
                farmhand (bean's overalls idea, Zelda proportions).
  C3 "MOSS"     leaf-sprout hair, earth jacket + yellow scarf — the whimsical
                bug-keeper wildcard.

Gate output: down idle + 2-frame forward walk (mirror trick) + a bean-style
3/4 side idle per character.
Run: python3 tools/player_sprites/player_designs2.py
-> previews/player/designs2/{card.png, C?_walk.gif}
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
from player_sprites import pixkit  # noqa: E402

OUT = os.path.normpath(os.path.join(HERE, "..", "_generated", "previews",
                                    "player", "designs2"))

# Shared legend additions per character live in PALS below.
# o outline | S/s/z skin | e eye | m mouth | H/h/g hair | T/t/u shirt/tunic |
# L/l/v pants/dress | B/b boots | Y/y/x hat-straw | C/c/q accent (strap/scarf)

PALS = {
    "C1_scout": {
        "o": (24, 20, 24, 255),
        "S": (250, 210, 158, 255), "s": (238, 190, 136, 255), "z": (198, 144, 100, 255),
        "e": (30, 28, 36, 255), "m": (172, 106, 84, 255),
        "H": (216, 124, 62, 255), "h": (184, 96, 44, 255), "g": (138, 66, 30, 255),  # ginger
        "T": (128, 152, 84, 255), "t": (102, 128, 62, 255), "u": (72, 96, 44, 255),  # olive tunic
        "L": (146, 110, 72, 255), "l": (120, 88, 56, 255), "v": (90, 64, 40, 255),
        "B": (168, 76, 56, 255), "b": (132, 54, 40, 255),                            # red-brown boots
        "Y": (234, 206, 124, 255), "y": (206, 174, 92, 255), "x": (164, 132, 62, 255),  # straw hat
        "C": (94, 70, 52, 255), "c": (74, 54, 40, 255),                              # satchel strap
    },
    "C2_juniper": {
        "o": (24, 20, 24, 255),
        "S": (244, 198, 150, 255), "s": (230, 178, 128, 255), "z": (188, 134, 94, 255),
        "e": (30, 28, 36, 255), "m": (176, 110, 86, 255),
        "H": (92, 70, 60, 255), "h": (66, 50, 44, 255), "g": (44, 34, 30, 255),      # dark bob
        "T": (242, 234, 210, 255), "t": (222, 212, 184, 255), "u": (184, 172, 142, 255),  # cream shirt
        "L": (110, 156, 200, 255), "l": (84, 128, 176, 255), "v": (58, 96, 140, 255),     # sky overalls
        "B": (160, 112, 66, 255), "b": (124, 84, 48, 255),
        "Y": (236, 130, 140, 255), "y": (204, 96, 110, 255), "x": (158, 64, 80, 255),     # hairpin
        "C": (84, 128, 176, 255), "c": (58, 96, 140, 255),
    },
    "C3_moss": {
        "o": (24, 20, 24, 255),
        "S": (240, 204, 156, 255), "s": (226, 184, 134, 255), "z": (184, 138, 98, 255),
        "e": (30, 28, 36, 255), "m": (170, 108, 86, 255),
        "H": (122, 178, 84, 255), "h": (90, 148, 62, 255), "g": (58, 110, 42, 255),  # leaf sprout
        "T": (146, 110, 78, 255), "t": (118, 86, 60, 255), "u": (88, 62, 44, 255),   # earth jacket
        "L": (104, 94, 78, 255), "l": (82, 74, 60, 255), "v": (60, 54, 44, 255),
        "B": (94, 78, 96, 255), "b": (68, 56, 72, 255),                              # plum boots
        "Y": (240, 198, 88, 255), "y": (212, 166, 60, 255), "x": (166, 124, 40, 255),  # yellow scarf
        "C": (240, 198, 88, 255), "c": (212, 166, 60, 255),
    },
}

# ============================ C1 SCOUT (18x22) ===============================
# Straw hat crown from above; ginger tufts wider than the body; tiny eyes low;
# olive tunic w/ satchel strap; feet nubs. Head rows 0-12, body 13-18, feet 19-21.
C1_DOWN = """
......oooooo......
....ooYYYYYYoo....
...oYYYYYYYYYYo...
..oYYYYYYYYYYYYo..
.oyYYYYYYYYYYYyyo.
.oxyyyyyyyyyyyyxo.
.oHHhhhhhhhhhhHHo.
oHHhhhhhhhhhhhhHHo
oHhhSSSSSSSSSShhHo
oHhsSeSSSSSSeSshHo
.ohsSeSSSSSSeSsho.
..ozsSSSmmSSSzo...
...ozzsssssszzo...
...oTTTTTTTTTTo...
..oTtCttttttttTo..
..oSttCtttttttSo..
..ostttCttttttso..
...ottttCttttto...
...ouuttttttuuo...
....oLLooooLLo....
....oBbooooBbo....
....ooo....ooo....
"""

# step pose: left foot forward (drawn 1px lower + out), arms alternate
C1_STEP = """
......oooooo......
....ooYYYYYYoo....
...oYYYYYYYYYYo...
..oYYYYYYYYYYYYo..
.oyYYYYYYYYYYYyyo.
.oxyyyyyyyyyyyyxo.
.oHHhhhhhhhhhhHHo.
oHHhhhhhhhhhhhhHHo
oHhhSSSSSSSSSShhHo
oHhsSeSSSSSSeSshHo
.ohsSeSSSSSSeSsho.
..ozsSSSmmSSSzo...
...ozzsssssszzo...
...oTTTTTTTTTTo...
..oTtCttttttttTo..
..oSttCtttttttto..
..ostttCttttttto..
...ottttCttttto...
...ouuttttttuuo...
...oLLooooooLLo...
...oBbo....oBbo...
...oooo.....ooo...
"""

# bean-style 3/4 side (facing left): crown + tufts kept, face strip leading.
C1_LEFT = """
......oooooo......
....ooYYYYYYoo....
...oYYYYYYYYYYo...
..oYYYYYYYYYYYYo..
.oyYYYYYYYYYYYyyo.
.oxyyyyyyyyyyyyxo.
.oHHhhhhhhhhhHHo..
.oHhhhhhhhhhhhHHo.
.oSShhhhhhhhhhhHo.
.oSeSShhhhhhhhsho.
.oseSShhhhhhhsho..
..ozsShhhhhhzo....
...ozzsshhzzo.....
...oTTTTTTTTTo....
..oTtCtttttttto...
..oSttCttttttuo...
..ostttCtttttuo...
...ottttCtttuo....
...ouutttttuuo....
....oLLooLLoo.....
....oBbooBbo......
....oooooooo......
"""

# ============================ C2 JUNIPER (18x22) =============================
# Dark bob with big side tufts + a pink hairpin; cream shirt; SKY-BLUE
# overall dress (bib straps over the shoulders); little boots.
C2_DOWN = """
.....oooooooo.....
...ooHHHHHHHHoo...
..oHHHHHHHHHHHHo..
.oHHHHHHHHHHHHHHo.
.oHHHHHHHHHHHYyHo.
oHHhhhhhhhhhhhYyHo
oHHhSSSSSSSSSShhHo
oHhsSeSSSSSSeSshHo
.ohsSeSSSSSSeSsho.
..ozsSSSmmSSSzo...
...ozzsssssszzo...
...oTTLLTTLLTTo...
..oTtoLtttLottTo..
..oStoLLLLLLotSo..
..ostoLlllllLoso..
...otoLlllllLoto..
...ouoLllllllLuo..
....oLLllllLLo....
....oLooooooLo....
....oBbo..oBbo....
....oooo..oooo....
..................
"""

C2_STEP = """
.....oooooooo.....
...ooHHHHHHHHoo...
..oHHHHHHHHHHHHo..
.oHHHHHHHHHHHHHHo.
.oHHHHHHHHHHHYyHo.
oHHhhhhhhhhhhhYyHo
oHHhSSSSSSSSSShhHo
oHhsSeSSSSSSeSshHo
.ohsSeSSSSSSeSsho.
..ozsSSSmmSSSzo...
...ozzsssssszzo...
...oTTLLTTLLTTo...
..oTtoLtttLottto..
..oStoLLLLLLotto..
..ostoLlllllLoso..
...otoLlllllLoto..
...ouoLllllllLuo..
...oLLllllLLoo....
...oLoooooLLo.....
...oBbo..oBbbo....
...oooo...oooo....
..................
"""

C2_LEFT = """
.....oooooooo.....
...ooHHHHHHHHoo...
..oHHHHHHHHHHHHo..
.oHHHHHHHHHHHHHHo.
.oYyHHHHHHHHHHHo..
.oYyhhhhhhhhhhHo..
.oSShhhhhhhhhhHo..
.oSeSShhhhhhhhho..
.oseSShhhhhhhso...
..ozsShhhhhhzo....
...ozzsshhzzo.....
...oTTLLTTTTTo....
..oTtoLttttttto...
..oStoLLLLLttuo...
..ostoLlllLttuo...
...otoLlllLtuo....
...ouoLllllLuo....
....oLLllLLoo.....
....oLoooLo.......
....oBbooBbo......
....oooooooo......
..................
"""

# ============================ C3 MOSS (18x22) ================================
# Leaf-sprout hair (two big leaf tufts!), earth jacket, yellow scarf wrap,
# plum boots — the whimsical bug-keeper.
C3_DOWN = """
.......oHHo.......
.....ooHhhHoo.....
...ooHHHhhHHHoo...
..oHHHHHhhHHHHHo..
.oHHhhhhhhhhhhHHo.
.oHhhhhhhhhhhhhHo.
.ohhhSSSSSSSShhho.
ohhsSeSSSSSSeSshho
.ohsSeSSSSSSeSsho.
..ozsSSSmmSSSzo...
...ozzsssssszzo...
...oYYYYYYYYYYo...
..oYyyyyyyyyyyYo..
..oTttttttttttto..
..oSttttttttttSo..
..osttttttttttso..
...otttttttttto...
...ouuttttttuuo...
....oLLooooLLo....
....oBbooooBbo....
....ooo....ooo....
..................
"""

C3_STEP = """
.......oHHo.......
.....ooHhhHoo.....
...ooHHHhhHHHoo...
..oHHHHHhhHHHHHo..
.oHHhhhhhhhhhhHHo.
.oHhhhhhhhhhhhhHo.
.ohhhSSSSSSSShhho.
ohhsSeSSSSSSeSshho
.ohsSeSSSSSSeSsho.
..ozsSSSmmSSSzo...
...ozzsssssszzo...
...oYYYYYYYYYYo...
..oYyyyyyyyyyyYo..
..oTttttttttttto..
..oSttttttttttto..
..osttttttttttso..
...otttttttttto...
...ouuttttttuuo...
...oLLooooooLLo...
...oBbo....oBbo...
...oooo.....ooo...
..................
"""

C3_LEFT = """
.......oHHo.......
.....ooHhhHoo.....
...ooHHHhhHHHoo...
..oHHHHHhhHHHHo...
.oHHhhhhhhhhhHo...
.oHhhhhhhhhhhho...
.oSShhhhhhhhhho...
.oSeSShhhhhhhho...
.oseSShhhhhhso....
..ozsShhhhhzo.....
...ozzsshzzo......
...oYYYYYYYYo.....
..oYyyyyyyyyYo....
..oTttttttttto....
..oSttttttttuo....
..osttttttttuo....
...otttttttto.....
...ouutttttuo.....
....oLLooLLo......
....oBbooBbo......
....oooooooo......
..................
"""

CHARS = {
    "C1_scout": (C1_DOWN, C1_STEP, C1_LEFT),
    "C2_juniper": (C2_DOWN, C2_STEP, C2_LEFT),
    "C3_moss": (C3_DOWN, C3_STEP, C3_LEFT),
}


def main():
    from PIL import Image
    card = []
    for name, (down, step, left) in CHARS.items():
        pal = PALS[name]
        rows_d = pixkit.parse(down)
        rows_s = pixkit.parse(step)
        rows_l = pixkit.parse(left)
        for rows, label in ((rows_d, "down"), (rows_s, "step"), (rows_l, "left")):
            bad = sorted({c for r in rows for c in r if c != "." and c not in pal})
            assert not bad, (name, label, bad)
        idle = pixkit.render(rows_d, pal)
        stepA = pixkit.render(rows_s, pal)
        stepB = pixkit.render(pixkit.mirror(rows_s), pal)   # the LTTP mirror trick
        side = pixkit.render(rows_l, pal)
        pixkit.walk_gif([stepA, idle, stepB, idle],
                        os.path.join(OUT, f"{name}_walk.gif"), scale=8, ms=130)
        card += [idle, stepA, stepB, side]
    pixkit.save(pixkit.contact_sheet(card, cols=4, scale=8),
                os.path.join(OUT, "card.png"))
    print(f"designs2 -> {OUT} (rows: scout, juniper, moss; "
          f"cols: idle, stepA, stepB(mirror), side)")


if __name__ == "__main__":
    main()
