#!/usr/bin/env python3
"""Build a one-page HTML dashboard of a zone's CURRENT ecology + perf charts, so the human can see the
whole picture at a glance ("see what I see"). Written to <zone>/current/index.html and regenerated by
run_config.py at the end of every run. Open it in a browser — the PNGs live alongside it. Pure stdlib.

  python3 tools/make_dashboard.py --zone village_21_B
"""
import argparse
import os
import time

# (filename in <zone>/current/, human description) — order = top-to-bottom on the page. Perf first.
CHARTS = [
    ("perf.png", "Performance — CPU by species/phase, throughput vs the 100ms budget, dark (un-measured) time, per-bug, GC"),
    ("population.png", "Population — per-species counts over game-days"),
    ("interactions.png", "Interactions — births by source / deaths by cause / predation matrix"),
    ("phase_portraits.png", "Phase portraits — predator-vs-prey trajectories"),
    ("bugmap_contact_sheet.png", "Bug distribution — daily spatial maps"),
]


def build(zone, charts_root):
    cur = os.path.join(charts_root, zone, "current")
    os.makedirs(cur, exist_ok=True)
    out = ["<!doctype html><meta charset=utf-8><title>%s — dashboard</title>" % zone,
           "<style>body{background:#111;color:#ddd;font:14px/1.4 system-ui,sans-serif;margin:0;padding:24px}"
           "h1{font-size:20px;margin:0 0 2px}h2{font-size:15px;color:#9cf;margin:28px 0 6px}"
           "img{max-width:100%;border:1px solid #333;background:#fff;display:block}"
           ".t{color:#888;font-size:12px}a{color:#9cf}</style>",
           "<h1>%s — current charts</h1>" % zone,
           "<div class=t>generated %s — the LATEST run; history in <code>../archive/</code></div>"
           % time.strftime("%Y-%m-%d %H:%M:%S")]
    for fn, desc in CHARTS:
        p = os.path.join(cur, fn)
        out.append("<h2>%s</h2>" % desc)
        if os.path.exists(p):
            out.append("<img src='%s?v=%d'>" % (fn, int(os.path.getmtime(p))))  # ?v= busts browser cache
        else:
            out.append("<div class=t>(not generated yet: %s)</div>" % fn)
    out.append("<h2>data</h2><div class=t>CSVs in <code>../archive/&lt;run&gt;/</code> and "
               "<code>tools/_generated/ecology_charts/</code> (perf_log_*, perf_sys_*).</div>")
    path = os.path.join(cur, "index.html")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    return path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--zone", default="village_21_B")
    args = ap.parse_args()
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    charts_root = os.path.join(root, "tools", "_generated", "ecology_charts")
    path = build(args.zone, charts_root)
    print("dashboard -> %s" % path)


if __name__ == "__main__":
    main()
