#!/usr/bin/env python3
"""Hand-authored vegetable sprites (Pipeline B, pixkit text grids).

4 crops x 4 growth stages at 16px-wide NATIVE (renders 1:1 at PPU 16, unlike
the 32px gpt stage art that downscales) + harvest icons ({veg}.png) + seed
packet icons (seed_{veg}_icon.png) — 16x16 grids emitted x2-nearest as 32x32.

Outputs: Resources/Objects/plant_{veg}_stage{N}.png (+ plant_{veg}.png base
fallback = stage3), Resources/Items/{veg}.png + seed_{veg}_icon.png.
Preview -> tools/_generated/previews/veg/stages.png

Run: python3 tools/veg_sprites.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from player_sprites import pixkit  # noqa: E402

RES = os.path.normpath(os.path.join(HERE, "..", "BugFarmerClient", "Assets", "Resources"))
PREVIEW = os.path.join(HERE, "_generated", "previews", "veg")

# shared chars: o outline | F/f/d foliage light/base/dark | D/E tilled soil
# light/dark | A/a/x crop accent light/base/dark | t stem brown | C/c head tones
BASE = {
    "o": (24, 20, 24, 255),
    "F": (80, 150, 70, 255), "f": (55, 120, 55, 255), "d": (40, 85, 40, 255),
    "D": (84, 58, 36, 255), "E": (64, 44, 28, 255),
    "t": (120, 90, 60, 255),
}
ACCENTS = {
    "carrot":   {"A": (236, 140, 52, 255), "a": (206, 108, 34, 255), "x": (160, 78, 22, 255)},
    "pumpkin":  {"A": (240, 150, 58, 255), "a": (212, 116, 36, 255), "x": (164, 84, 24, 255)},
    "cabbage":  {"A": (206, 228, 150, 255), "a": (178, 204, 120, 255), "x": (140, 170, 92, 255)},
    "eggplant": {"A": (124, 70, 160, 255), "a": (94, 48, 128, 255), "x": (66, 32, 94, 255)},
}


def P(veg):
    pal = dict(BASE)
    pal.update(ACCENTS[veg])
    return pal


# ---- stage grids (16 wide; heights grow per stage) ---------------------------
SPROUT = """
................
................
................
................
................
......f..F......
......d..f......
.......dd.......
................
....DDEDDED.....
...DEDDDEDDE....
................
"""

CARROT = {
    0: SPROUT,
    1: """
................
................
....F.....F.....
....f..F..f.....
.....d.f.d......
......dfd.......
.......f........
.......d........
....DDEDDED.....
...DEDDDEDDE....
................
................
""",
    2: """
................
..F....F....F...
..f.F..f..F.f...
...ff..f.ff.....
....df.f.fd.....
.....dfffd......
......fff.......
.......f........
.......d........
....DDEDDED.....
...DEDADEDDE....
................
""",
    3: """
.F..F......F..F.
.f.Ff..FF..fF.f.
..ffF..ff..Fff..
...ff.ffff.ff...
....dffffffd....
.....dffffd.....
......ffff......
.......ff.......
......oAAo......
.....oAAAao.....
....DoAaaoED....
...DEDoaaoDDE...
""",
}

PUMPKIN = {
    0: SPROUT,
    1: """
................
................
...F......F.....
..FFf....fFf....
..fff.f..fff....
...d.df.fd......
......dfd.......
.......f........
....DDEDDED.....
...DEDDDEDDE....
................
................
""",
    2: """
................
..FFf......F....
..fff..f..FFf...
...d..df..fff...
....ffd.f..d....
........f.......
......offfo.....
.....offfffo....
.....oFffFo.....
....DoffffoD....
...DEDoffoDDE...
................
""",
    3: """
..FFf......FFf..
..fff..tt..fff..
...d...tt...d...
....f.ottto.....
....oAAAAAAo....
...oAAaAAaAAo...
..oAaAAaaAAaAo..
..oAaAAaaAAaAo..
..oxaAAaaAAaxo..
...oxaaxxaaxo...
..D.oxxxxxxoED..
...DEDoxxoDDE...
""",
}

CABBAGE = {
    0: SPROUT,
    1: """
................
................
...F........F...
..Fff..ff..ffF..
..fff.fFf.fff...
...d..fff..d....
.....dfffd......
......fff.......
....DDEDDED.....
...DEDDDEDDE....
................
................
""",
    2: """
................
...F........F...
..Fff.oAo..ffF..
..ff.oAAao.ff...
...f.oAaao.f....
...d.oaaxo.d....
....f.oxo.f.....
.....dfffd......
....DDEDDED.....
...DEDDDEDDE....
................
................
""",
    3: """
................
....oAAAAo......
...oAAAAAAo.....
..FoAAaAAaoF....
..foAaAAaaof....
..foAaaAaaof....
..ffoaaxaaoff...
...d.oaxxo.d....
....foxxof......
....DDEDDED.....
...DEDDDEDDE....
................
""",
}

EGGPLANT = {
    0: SPROUT,
    1: """
................
................
....F.....F.....
...Fff...fF.....
...fff.f.ff.....
....d.dfd.......
......fff.......
.......f........
....DDEDDED.....
...DEDDDEDDE....
................
................
""",
    2: """
................
...F...F...F....
..Fff.fFf.ffF...
..fff.fff.fff...
...dA.fdf.Ad....
....f..f..f.....
.....dfffd......
......fff.......
.......f........
....DDEDDED.....
...DEDDDEDDE....
................
""",
    3: """
...F...FF...F...
..Fff.ffff.ffF..
..fffffffffff...
...df.f..f.fd...
....f.f..f.f....
...oAof..foAo...
...oAAo..oAAo...
...oAao..oAao...
...oaao..oaao...
....oxo..oxo....
....DDEDDED.....
...DEDDDEDDE....
""",
}

# ---- icons (16x16, emitted x2 as 32x32) --------------------------------------
ICONS = {
    "carrot": """
.............FF.
...........FFf..
..........Ff....
.........fff....
........oAof....
.......oAAo.....
......oAAao.....
.....oAAao......
....oAAao.......
...oAaao........
...oAao.........
..oAao..........
..oao...........
..oxo...........
...o............
................
""",
    "pumpkin": """
................
......tt........
......tt........
....ottto.......
..oAAAAAAAAo....
.oAAaAAAAaAAo...
oAaAAaAAaAAaAo..
oAaAAaAAaAAaAo..
oAaAAaAAaAAaAo..
oxaAAaAAaAAaxo..
.oxaaxaaxaaxo...
..oxxxxxxxxo....
...oxxxxxxo.....
.....oooo.......
................
................
""",
    "cabbage": """
................
.....oooo.......
...ooAAAAoo.....
..oAAAAAAAAo....
.oAAaAAAAaAAo...
.oAaAAaaAAaAo...
oAAaAaAAaAaAAo..
oAaAAaAAaAAaAo..
oAaAAaaAaaAaAo..
.oaAaAAaAAaao...
.oaaAaaaAaaao...
..oaaaxxaaao....
...oxaxxaxo.....
.....oxxo.......
................
................
""",
    "eggplant": """
................
..........Ff....
........Ffff....
.......offf.....
......oAAof.....
.....oAAAAo.....
....oAAaAAo.....
...oAAaAAao.....
..oAAaAAao......
..oAaAAaao......
..oAaAaao.......
..oaAaao........
..oaaao.........
...oxxo.........
....oo..........
................
""",
}

SEED_PACKET = """
................
...oooooooooo...
..oYYYYYYYYYYo..
..oYyyyyyyyyYo..
..oYyAAAAAAyYo..
..oYyAAaaAAyYo..
..oYyAaaaaAyYo..
..oYyAAaaAAyYo..
..oYyAAAAAAyYo..
..oYyyyyyyyyYo..
..oYYYYYYYYYYo..
..oYyYyYyYyYYo..
...oooooooooo...
................
................
................
"""
PACKET_BASE = {"Y": (236, 226, 198, 255), "y": (204, 190, 156, 255)}


def render(grid, pal):
    return pixkit.render(pixkit.parse(grid), pal, mode="baked")


def main():
    cells, labels = [], []
    for veg, stages in (("carrot", CARROT), ("pumpkin", PUMPKIN),
                        ("cabbage", CABBAGE), ("eggplant", EGGPLANT)):
        pal = P(veg)
        for n in range(4):
            im = render(stages[n], pal)
            pixkit.save(im, os.path.join(RES, "Objects", f"plant_{veg}_stage{n}.png"))
            cells.append(im)
        # base fallback sprite = the mature stage
        pixkit.save(render(stages[3], pal), os.path.join(RES, "Objects", f"plant_{veg}.png"))

        # icons: 16x16 grids -> 32x32 nearest
        icon = render(ICONS[veg], pal)
        pixkit.save(icon.resize((32, 32), 0), os.path.join(RES, "Items", f"{veg}.png"))
        spal = dict(pal)
        spal.update(PACKET_BASE)
        seed = render(SEED_PACKET, spal)
        pixkit.save(seed.resize((32, 32), 0), os.path.join(RES, "Items", f"seed_{veg}_icon.png"))
        cells += [icon, seed]

    pixkit.save(pixkit.contact_sheet(cells, cols=6, scale=8),
                os.path.join(PREVIEW, "stages.png"))
    print(f"veg sprites -> {RES}/Objects + /Items; preview -> {PREVIEW}/stages.png")


if __name__ == "__main__":
    main()
